Hormona.App/Hormona.App.Presentacion/Pages/BDEndocrinos/Create.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Hormona.App.Dominio;
using Hormona.App.Persistencia;

namespace Hormona.App.Pages_BDEndocrinos
{
    public class CreateModel : PageModel
    {
private readonly IRepositorioEndocrino RepositorioEndocrino;
        [BindProperty]
        public Endocrino Endocrino{get; set;}
        public CreateModel(IRepositorioEndocrino RepositorioEndocrino) {
            this.RepositorioEndocrino = RepositorioEndocrino;
        }
        public void OnGet()
        {
        }
        public IActionResult OnpostSave(){
          //  if(ModelState.IsValid){
                Endocrino=RepositorioEndocrino.AddEndocrino(Endocrino);
                return RedirectToPage("Index");
           // }
           // else{
               // return Page();
            //}
        }
    }
}

Hormona.App/Hormona.App.Presentacion/Pages/BDEndocrinos/Details.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Hormona.App.Dominio;
using Hormona.App.Persistencia;


namespace Hormona.App.Pages_BDEndocrinos
{
    public class DetailsModel : PageModel
    {
         private readonly IRepositorioEndocrino RepositorioEndocrino; 
        public Endocrino Endocrino{get; set;}   
        public DetailsModel(IRepositorioEndocrino RepositorioEndocrino){
            this.RepositorioEndocrino= RepositorioEndocrino;

        }
        public IActionResult OnGet(int id)
        {
            Endocrino=RepositorioEndocrino.GetEndocrino(id);
            if(Endocrino==null){
                return RedirectToPage(",/NotFound");
            }
            else{
                return Page();
            }
        }
    }
}

Hormona.App/Hormona.App.Presentacion/Pages/BDFamiliar/Create.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Hormona.App.Dominio;
using Hormona.App.Persistencia;

namespace Hormona.App.Pages_BDFamiliar
{
    public class CreateModel : PageModel
    {
private readonly IRepositorioFamiliar RepositorioFamiliar;
        [BindProperty]
        public Familiar Familiar{get; set;}
        public CreateModel(IRepositorioFamiliar RepositorioFamiliar) {
            this.RepositorioFamiliar = RepositorioFamiliar;
        }
        public void OnGet()
        {
        }
        public IActionResult OnpostSave(){
          //  if(ModelState.IsValid){
                Familiar=RepositorioFamiliar.AddFamiliar(Familiar);
                return RedirectToPage("Index");
           // }
           // else{
               // return Page();
            //}
        }
    }
}

Hormona.App/Hormona.App.Presentacion/Pages/BDFamiliar/Delete.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Hormona.App.Dominio;
using Hormona.App.Persistencia;

namespace Hormona.App.Pages_BDFamiliar
{
    public class DeleteModel : PageModel
    {
 private readonly IRepositorioFamiliar RepositorioFamiliar;
        [BindProperty]
        public Familiar Familiar {get; set;}
        public DeleteModel(IRepositorioFamiliar RepositorioFamiliar){
           this.RepositorioFamiliar = RepositorioFamiliar;
        }
        public IActionResult OnGet(int id)
        {
                Familiar=RepositorioFamiliar.GetFamiliar(id);
                if(Familiar==null){
                    return RedirectToPage("./NotFound");
                }
                else{
                    return Page();
                }
        }
        public IActionResult OnPostDelete(){
            RepositorioFamiliar.DelateFamiliar(Familiar.id);
            return RedirectToPage("Index");
        }
    }
}

Hormona.App/Hormona.App.Presentacion/Pages/BDFamiliar/Details.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Hormona.App.Dominio;
using Hormona.App.Persistencia;


namespace Hormona.App.Pages_BDFamiliar
{
    public class DetailsModel : PageModel
    {
  private readonly IRepositorioFamiliar RepositorioFamiliar; 
        public Familiar Familiar {get; set;}   
       
        public DetailsModel(IRepositorioFamiliar RepositorioFamiliar){
            this.RepositorioFamiliar= RepositorioFamiliar;

             }
        public IActionResult OnGet(int id)
        {
            Familiar=RepositorioFamiliar.GetFamiliar(id);
            if(Familiar==null){
                return RedirectToPage(",/NotFound");
            }
            else{
                return Page();
            }
        }
    }
}

Hormona.App/Hormona.App.Presentacion/Pages/BDFamiliar/Edit.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Hormona.App.Dominio;
using Hormona.App.Persistencia;

namespace Hormona.App.Pages_BDFamiliar
{
    public class EditModel : PageModel
    {
  private readonly IRepositorioFamiliar RepositorioFamiliar;
        [BindProperty]
        public Familiar Familiar {get; set;}
        public  EditModel(IRepositorioFamiliar RepositorioFamiliar){
            this.RepositorioFamiliar = RepositorioFamiliar;
        }
        public IActionResult OnGet(int id)
        {
                Familiar=RepositorioFamiliar.GetFamiliar(id);
                if(Familiar==null){
                    return RedirectToPage("./NotFound");
                }
                else{
                    return Page();
                }
        }
        public IActionResult OnPostEdit(){
            Familiar=RepositorioFamiliar.UpdateFamiliar(Familiar);
           return RedirectToPage("Index");
    }
}
}

Hormona.App/Hormona.App.Presentacion/Pages/BDPacientes/AddPatrones.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Hormona.App.Dominio;
using Hormona.App.Persistencia;

namespace Hormona.App.Pages_BDPacientes
{
    public class AddPatronesModel : PageModel
    {
        private readonly IRepositorioPaciente RepositorioPaciente;
        [BindProperty]
        public PatronDeCrecimineto PatronDeCrecimineto{get; set;} 
       [BindProperty]
        public Paciente Paciente{get; set;}
       public AddPatronesModel(IRepositorioPaciente RepositorioPaciente){
           this.RepositorioPaciente = RepositorioPaciente;
        }
        public IActionResult OnGet(int id)
        {
            Paciente=RepositorioPaciente.GetPaciente(id);
            if(Paciente==null){
                return RedirectToPage("./NotFound");
            }
            else{
                return Page();
           }
        }
        public IActionResult OnPostSave(){
            if(Paciente.id>0){
                var paciente=RepositorioPaciente.GetPaciente(Paciente.id);
                if(Paciente!=null){
                    if(paciente.Patrones!=null){
                        paciente.Patrones.Add(PatronDeCrecimineto);
                    }
                    else{
                        paciente.Patrones=new List<PatronDeCrecimineto>{
                           new PatronDeCrecimineto{
                                fechaHora=PatronDeCrecimineto.fechaHora,
                                valor=PatronDeCrecimineto.valor,
                               patronesDeCrecimiento=PatronDeCrecimineto.patronesDeCrecimiento

                            }
                        };
                    }
                    RepositorioPaciente.UpdatePaciente(paciente);
               }
                return RedirectToPage("Index");
            }
            else{
                return Page();
            }
       }
    }
}

Hormona.App/Hormona.App.Presentacion/Pages/BDPacientes/AsignarEndocrinos.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Hormona.App.Dominio;
using Hormona.App.Persistencia;


namespace Hormona.App.Pages_BDPacientes
{
    public class AsignarEndocrinosModel : PageModel
    {
 private readonly IRepositorioEndocrino RepositorioEndocrino;
        private readonly IRepositorioPaciente RepositorioPaciente;
        public IEnumerable<Endocrino>Endocrinos{get; set;}
        [BindProperty]
        public int Endocrinoid{get; set;}
        [BindProperty]

        public Endocrino Endocrino{get; set;}
        [BindProperty]

        public Paciente Paciente{get; set;}
        public AsignarEndocrinosModel(IRepositorioEndocrino RepositorioEndocrino,IRepositorioPaciente RepositorioPaciente){
            this.RepositorioEndocrino = RepositorioEndocrino;
            this.RepositorioPaciente = RepositorioPaciente;
        }


        public IActionResult OnGet(int id)
        {
            Endocrinos=RepositorioEndocrino.GetAllEndocrinos();
            Paciente=RepositorioPaciente.GetPaciente(id);
            if(Paciente==null){
                return RedirectToPage("./NotFound");
            }
            else{
                return Page();
            }
        }
        public IActionResult OnPostToAssign(int Endocrinoid){
            Endocrino=RepositorioPaciente.AsignarEndocrino(Paciente.id,Endocrinoid);
            return RedirectToPage("Index");
    }
}
}

Hormona.App/Hormona.App.Presentacion/Pages/BDPacientes/AsignarFamiliar.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Hormona.App.Dominio;
using Hormona.App.Persistencia;

namespace Hormona.App.Pages_BDPacientes
{
    public class AsignarFamiliarModel : PageModel
    {
 private readonly IRepositorioFamiliar RepositorioFamiliar;
        private readonly IRepositorioPaciente RepositorioPaciente;
        public IEnumerable<Familiar>Familiares{get; set;}
        [BindProperty]
        public int familiarid{get; set;}
        [BindProperty]

        public Familiar Familiar{get; set;}
        [BindProperty]

        public Paciente Paciente{get; set;}
        public AsignarFamiliarModel( IRepositorioFamiliar RepositorioFamiliar,IRepositorioPaciente RepositorioPaciente){
            this.RepositorioFamiliar = RepositorioFamiliar;
            this.RepositorioPaciente = RepositorioPaciente;
        }


        public IActionResult OnGet(int id)
        {
            Familiares=RepositorioFamiliar.GetAllFamiliares();
            Paciente=RepositorioPaciente.GetPaciente(id);
            if(Paciente==null){
                return RedirectToPage("./NotFound");
            }
            else{
                return Page();
            }
        }
        public IActionResult OnPostToAssign(int familiarid){
            Familiar=RepositorioPaciente. AsignarFamiliar(Paciente.id,familiarid);
            return RedirectToPage("Index");
        }
    }
}

Hormona.App/Hormona.App.Presentacion/Pages/BDPacientes/AsignarPediatra.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Hormona.App.Dominio;
using Hormona.App.Persistencia;

namespace Hormona.App.Pages_BDPacientes
{
    public class AsignarPediatraModel : PageModel
    {
        private readonly IRepositorioPediatra RepositorioPediatra;
        private readonly IRepositorioPaciente RepositorioPaciente;
        public IEnumerable<Pediatra>Pediatras{get; set;}
        [BindProperty]
        public int pediatraid{get; set;}
        [BindProperty]

        public Pediatra Pediatra{get; set;}
        [BindProperty]

        public Paciente Paciente{get; set;}
        public AsignarPediatraModel(IRepositorioPediatra RepositorioPediatra,IRepositorioPaciente RepositorioPaciente){
            this.RepositorioPediatra = RepositorioPediatra;
            this.RepositorioPaciente = RepositorioPaciente;
        }


        public IActionResult OnGet(int id)
        {
            Pediatras=RepositorioPediatra.GetAllPediatras();
            Paciente=RepositorioPaciente.GetPaciente(id);
            if(Paciente==null){
                return RedirectToPage("./NotFound");
            }
            else{
                return Page();
            }
        }
        public IActionResult OnPostToAssign(int pediatraid){
            Pediatra=RepositorioPaciente.AsignarPediatra(Paciente.id,pediatraid);
            return RedirectToPage("Index");
        }
    }
}

Hormona.App/Hormona.App.Presentacion/Pages/BDPacientes/Create.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Hormona.App.Dominio;
using Hormona.App.Persistencia;

namespace Hormona.App.Pages_BDPacientes
{
    public class CreateModel : PageModel
    {
        private readonly IRepositorioPaciente RepositorioPaciente;
        [BindProperty]
        public Paciente Paciente{get; set;}
        public CreateModel(IRepositorioPaciente RepositorioPaciente){
            this.RepositorioPaciente =RepositorioPaciente;
        }
        public void OnGet()
        {
        }
         public IActionResult OnPostSave(){
            Paciente=RepositorioPaciente.AddPaciente(Paciente);
            return RedirectToPage("Index");
                
            }
}
}

Hormona.App/Hormona.App.Presentacion/Pages/BDPacientes/Delete.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Hormona.App.Dominio;
using Hormona.App.Persistencia;

namespace Hormona.App.Pages_BDPacientes
{
    public class DeleteModel : PageModel
    {
         private readonly IRepositorioPaciente RepositorioPaciente;
        [BindProperty]
        public Paciente Paciente {get; set;}
        public DeleteModel(IRepositorioPaciente RepositorioPaciente){
           this.RepositorioPaciente = RepositorioPaciente;
        }
        public IActionResult OnGet(int id)
        {
                Paciente=RepositorioPaciente.GetPaciente(id);
                if(Paciente==null){
                    return RedirectToPage("./NotFound");
                }
                else{
                    return Page();
                }
        }
        public IActionResult OnPostDelete(){
            RepositorioPaciente.DeletePaciente(Paciente.id);
            return RedirectToPage("Index");
        }
    }
}

Hormona.App/Hormona.App.Presentacion/Pages/BDPacientes/Details.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Hormona.App.Dominio;
using Hormona.App.Persistencia;
namespace Hormona.App.Pages_BDPacientes
{
    public class DetailsModel : PageModel
    {
         private readonly IRepositorioPaciente RepositorioPaciente; 
        public Paciente Paciente {get; set;}   
        public Pediatra Pediatra {get; set;}
        public DetailsModel(IRepositorioPaciente RepositorioPaciente){
            this.RepositorioPaciente= RepositorioPaciente;

        }
        public IActionResult OnGet(int id)
        {
            Paciente=RepositorioPaciente.GetPaciente(id);
            if(Paciente==null){
                return RedirectToPage(",/NotFound");
            }
            else{
                if(RepositorioPaciente.ConsultarPediatra(id)==null){
                    Pediatra=new Pediatra{
                        nombre="Sin Asignar"
                    };
                    Paciente.Pediatra=Pediatra;
                }else{
                    Paciente.Pediatra=RepositorioPaciente.ConsultarPediatra(id);
                }
                return Page();
            }

        }
    }
}

Hormona.App/Hormona.App.Presentacion/Pages/BDPacientes/Edit.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Hormona.App.Dominio;
using Hormona.App.Persistencia;

namespace Hormona.App.Pages_BDPacientes
{
    public class EditModel : PageModel
    {
        private readonly IRepositorioPaciente RepositorioPaciente;
        [BindProperty]
        public Paciente Paciente {get; set;}
        public  EditModel(IRepositorioPaciente RepositorioPaciente){
            this.RepositorioPaciente = RepositorioPaciente;
        }
        public IActionResult OnGet(int id)
        {
                Paciente=RepositorioPaciente.GetPaciente(id);
                if(Paciente==null){
                    return RedirectToPage("./NotFound");
                }
                else{
                    return Page();
                }
        }
        public IActionResult OnPostEdit(){
            Paciente=RepositorioPaciente.UpdatePaciente(Paciente);
           return RedirectToPage("Index");
        }
    }
}

Hormona.App/Hormona.App.Presentacion/Pages/MPacientes/Delete.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace Hormona.App.Pages_MPacientes
{
    public class DeleteModel : PageModel
    {
        public void OnGet()
        {
        }
    }
}

Hormona.App/Hormona.App.Presentacion/Pages/BDPacientes/AddPatrones.cshtml
@page
@model Hormona.App.Pages_BDPacientes.AddPatronesModel
@{
}
<h1>add Patrones de Crecimiento</h1>
<form method="post">
    <input type="hidden" asp-for="Paciente.id"/>
    <div class="form group">
        <label>Patrones de Crecimiento</label>
        <select asp.for="PatronDeCrecimiento.PatronesDeCrecimineto" class="form-control">
            <option value="0">peso</option>
            <option value="1">perimentroCefalico</option>
            <option value="2">talla</option>
            <option value="3">mediddaAbdominal</option>
        </select>
    </div>  
    <div class="form-group">
        <label>valor</label>
        <input asp-for="PatronDeCrecimineto.valor" class="form-control"/>
    </div>
    <div class="form-group">
        <label>fecha</label>
        <input asp-for="PatronDeCrecimineto.fechaHora" class="form-control"/>
    </div>
    <div class="form group">
        <button type="submit" class="btn btn-primary" asp-page-handler="Save">AddPatron</button>
        <a asp-page="./Index">Back To list</a>
    </div>

</form>

Hormona.App/Hormona.App.Presentacion/Pages/BDPacientes/AsignarEndocrinos.cshtml
@page
@model Hormona.App.Pages_BDPacientes.AsignarEndocrinosModel
@{
}
<form method="post">
    <input type="hidden" asp-for="Paciente.id">
    <h1>Asignar Endocrino</h1>
    <table class="table table=bordered">
        <thead >
            <tr>
            <th scoope="col">Nombre</th>
            <th scoope="col">Apellidos</th>
            <th scoope="col">Telefono</th>
            <th scoope="col">Sexo</th>
            <th scoope="col">Codigo</th>
          
            </tr>
        </thead>
        @foreach (var endocrino in Model.Endocrinos){
            <tbody>
                <tr>
                    <td>@endocrino.nombre</td>
                    <td>@endocrino.apellido</td>
                    <td>@endocrino.telefono</td>
                    <td>@endocrino.sexos</td>
                    <td>@endocrino.codigo</td>
                    <td>@endocrino.registro</td>
                    <td>
                        <input type="checkbox" name="endocrinoid" value="@endocrino.id"/>
                    </td>
                </tr>
            </tbody>
        }
        
    </table>
    <button type="submit" class="btn btn-primary" asp-page-handler="ToAssign">Asignar</button>
</form>

Hormona.App/Hormona.App.Presentacion/Pages/BDPacientes/AsignarFamiliar.cshtml
@page
@model Hormona.App.Pages_BDPacientes.AsignarFamiliarModel
@{
}
<form method="post">
    <input type="hidden" asp-for="Paciente.id">
    <h1>Asignar Familiar</h1>
    <table class="table table=bordered">
        <thead >
            <tr>
            <th scoope="col">Nombre</th>
            <th scoope="col">Apellidos</th>
            <th scoope="col">Telefono</th>
            <th scoope="col">Sexo</th>
            <th scoope="col">Documento</th>
            <th scoope="col">Parentesco</th>
            <th scoope="col">Email</th>
            
          
            </tr>
        </thead>
        @foreach (var familiar in Model.Familiares){
            <tbody>
                <tr>
                    <td>@familiar.nombre</td>
                    <td>@familiar.apellido</td>
                    <td>@familiar.telefono</td>
                    <td>@familiar.sexos</td>
                    <td>@familiar.documento</td>
                    <td>@familiar.parentesco</td>
                     <td>@familiar.email</td>
                    <td>
                        <input type="checkbox" name="familiarid" value="@familiar.id"/>
                    </td>
                </tr>
            </tbody>
        }
        
    </table>
    <button type="submit" class="btn btn-primary" asp-page-handler="ToAssign">Asignar</button>
</form>

Hormona.App/Hormona.App.Presentacion/Pages/BDPacientes/AsignarPediatra.cshtml
@page
@model Hormona.App.Pages_BDPacientes.AsignarPediatraModel
@{
}
<form method="post">
    <input type="hidden" asp-for="Paciente.id">
    <h1>Asignar Pediatra</h1>
    <table class="table table=bordered">
        <thead >
            <tr>
            <th scoope="col">Nombre</th>
            <th scoope="col">Apellidos</th>
            <th scoope="col">Telefono</th>
            <th scoope="col">Sexo</th>
            <th scoope="col">Codigo</th>
          
            </tr>
        </thead>
        @foreach (var pediatra in Model.Pediatras){
            <tbody>
                <tr>
                    <td>@pediatra.nombre</td>
                    <td>@pediatra.apellido</td>
                    <td>@pediatra.telefono</td>
                    <td>@pediatra.sexos</td>
                    <td>@pediatra.codigo</td>
                    <td>@pediatra.registro</td>
                    <td>
                        <input type="checkbox" name="pediatraid" value="@pediatra.id"/>
                    </td>
                </tr>
            </tbody>
        }
        
    </table>
    <button type="submit" class="btn btn-primary" asp-page-handler="ToAssign">Asignar</button>
</form>

Hormona.App/Hormona.App.Presentacion/Pages/BDPacientes/Create.cshtml
@page
@model Hormona.App.Pages_BDPacientes.CreateModel
@{
}

<form method="post">
    <div asp-validation-sumary="ModelOnly"></div>
    <div class="form-group">
        <label>Nombre</label>
        <input asp-for="Paciente.nombre" placeholder="Digite el nombre del paciente" class="form-control"/> 
    </div>
     <div class="form-group">
        <label>Apellidos</label>
        <input asp-for="Paciente.apellido" placeholder="Digite los apellidos del paciente" class="form-control"/>
    </div>
     <div class="form-group">
        <label>Telefono</label>
        <input asp-for="Paciente.telefono" placeholder="Digite el telefono del paciente" class="form-control"/> 
    </div>
     </div>
     <div class="form-group">
        <label>Documento</label>
        <input asp-for="Paciente.documento" placeholder="Digite el documento del paciente" class="form-control"/>
    </div>
    <label>Sexo</label>
     <div class="form-group">
        <select asp-for="Paciente.sexos" class="form-control">
            <option selected>Sexo..</option>
            <option value=0>Femenino</option>
            <option value=1>Masculino</option>
        </select>

    </div>
     </div>
     <div class="form-group">
        <label>Ciudad</label>
        <input asp-for="Paciente.ciudad" placeholder="Digite la ciudad del paciente" class="form-control"/>
    </div>
     </div>
     <div class="form-group">
        <label>Direccion</label>
        <input asp-for="Paciente.direccion" placeholder="Digite la direccion del paciente" class="form-control"/>
    </div>
     </div>
     <div class="form-group">
        <label>Longitud</label>
        <input asp-for="Paciente.longitud" placeholder="Digite la longitud del paciente" class="form-control"/>
    </div>
     </div>
     <div class="form-group">
        <label>Latitud</label>
        <input asp-for="Paciente.latitud" placeholder="Digite la latitud del paciente" class="form-control"/>
    </div>
     </div>
     <div class="form-group">
        <label>Fecha de Nacimineto</label>
        <input asp-for="Paciente.fechaDeNacimineto"  class="form-control"/>
    </div>
    <button type="submit" class="btn btn-primary" asp-page-handler="Save">Crear</button>
</form>

Hormona.App/Hormona.App.Presentacion/Pages/BDPacientes/Delete.cshtml
@page
@model Hormona.App.Pages_BDPacientes.DeleteModel
@{
}
<h1>Seguro quieres eliminar este paciente</h1>
<div>
    <h4>Paciente</h4>
    <d1 class="row">
        <dt class="col-sm-2">Nombre</dt>
        <dd class="col-sm-10">@Model.Paciente.nombre</dd>
         <dt class="col-sm-2">Apellido</dt>
        <dd class="col-sm-10">@Model.Paciente.apellido</dd>
         <dt class="col-sm-2">Telefono</dt>
        <dd class="col-sm-10">@Model.Paciente.telefono</dd>
         <dt class="col-sm-2">Sexo</dt>
        <dd class="col-sm-10">@Model.Paciente.sexos</dd>
         <dt class="col-sm-2">Fecha de Nacimineto</dt>
        <dd class="col-sm-10">@Model.Paciente.fechaDeNacimineto</dd>
         <dt class="col-sm-2">Documento</dt>
        <dd class="col-sm-10">@Model.Paciente.documento</dd>
         <dt class="col-sm-2">Latitud</dt>
        <dd class="col-sm-10">@Model.Paciente.latitud</dd>
         <dt class="col-sm-2">Longitud</dt>
        <dd class="col-sm-10">@Model.Paciente.longitud</dd>
        
  

    
    </d1>
</div>
<form method="post">
    <input type="hidden" asp-for="Paciente.id"/>
    <button type="submit" class="btn btn-primary" asp-page-handler="Delete">Delete</button>
<a asp-page="./Index">Back to list</a>
</form>