Hormona.App/Hormona.App.Presentacion/Pages/BDEndocrinos/Create.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Hormona.App.Dominio;
using Hormona.App.Persistencia;

namespace Hormona.App.Pages_BDEndocrinos
{
    public class CreateModel : PageModel
    {
private readonly IRepositorioEndocrino RepositorioEndocrino;
        [BindProperty]
        public Endocrino Endocrino{get; set;}
        public CreateModel(IRepositorioEndocrino RepositorioEndocrino) {
            this.RepositorioEndocrino = RepositorioEndocrino;
        }
        public void OnGet()
        {
        }
        public IActionResult OnpostSave(){
          //  if(ModelState.IsValid){
                Endocrino=RepositorioEndocrino.AddEndocrino(Endocrino);
                return RedirectToPage("Index");
           // }
           // else{
               // return Page();
            //}
        }
    }
}

Hormona.App/Hormona.App.Presentacion/Pages/BDEndocrinos/Details.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Hormona.App.Dominio;
using Hormona.App.Persistencia;


namespace Hormona.App.Pages_BDEndocrinos
{
    public class DetailsModel : PageModel
    {
         private readonly IRepositorioEndocrino RepositorioEndocrino; 
        public Endocrino Endocrino{get; set;}   
        public DetailsModel(IRepositorioEndocrino RepositorioEndocrino){
            this.RepositorioEndocrino= RepositorioEndocrino;

        }
        public IActionResult OnGet(int id)
        {
            Endocrino=RepositorioEndocrino.GetEndocrino(id);
            if(Endocrino==null){
                return RedirectToPage(",/NotFound");
            }
            else{
                return Page();
            }
        }
    }
}

Hormona.App/Hormona.App.Presentacion/Pages/BDFamiliar/Create.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Hormona.App.Dominio;
using Hormona.App.Persistencia;

namespace Hormona.App.Pages_BDFamiliar
{
    public class CreateModel : PageModel
    {
private readonly IRepositorioFamiliar RepositorioFamiliar;
        [BindProperty]
        public Familiar Familiar{get; set;}
        public CreateModel(IRepositorioFamiliar RepositorioFamiliar) {
            this.RepositorioFamiliar = RepositorioFamiliar;
        }
        public void OnGet()
        {
        }
        public IActionResult OnpostSave(){
          //  if(ModelState.IsValid){
                Familiar=RepositorioFamiliar.AddFamiliar(Familiar);
                return RedirectToPage("Index");
           // }
           // else{
               // return Page();
            //}
        }
    }
}

Hormona.App/Hormona.App.Presentacion/Pages/BDFamiliar/Delete.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Hormona.App.Dominio;
using Hormona.App.Persistencia;

namespace Hormona.App.Pages_BDFamiliar
{
    public class DeleteModel : PageModel
    {
 private readonly IRepositorioFamiliar RepositorioFamiliar;
        [BindProperty]
        public Familiar Familiar {get; set;}
        public DeleteModel(IRepositorioFamiliar RepositorioFamiliar){
           this.RepositorioFamiliar = RepositorioFamiliar;
        }
        public IActionResult OnGet(int id)
        {
                Familiar=RepositorioFamiliar.GetFamiliar(id);
                if(Familiar==null){
                    return RedirectToPage("./NotFound");
                }
                else{
                    return Page();
                }
        }
        public IActionResult OnPostDelete(){
            RepositorioFamiliar.DelateFamiliar(Familiar.id);
            return RedirectToPage("Index");
        }
    }
}

Hormona.App/Hormona.App.Presentacion/Pages/BDFamiliar/Details.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Hormona.App.Dominio;
using Hormona.App.Persistencia;


namespace Hormona.App.Pages_BDFamiliar
{
    public class DetailsModel : PageModel
    {
  private readonly IRepositorioFamiliar RepositorioFamiliar; 
        public Familiar Familiar {get; set;}   
       
        public DetailsModel(IRepositorioFamiliar RepositorioFamiliar){
            this.RepositorioFamiliar= RepositorioFamiliar;

             }
        public IActionResult OnGet(int id)
        {
            Familiar=RepositorioFamiliar.GetFamiliar(id);
            if(Familiar==null){
                return RedirectToPage(",/NotFound");
            }
            else{
                return Page();
            }
        }
    }
}

Hormona.App/Hormona.App.Presentacion/Pages/BDFamiliar/Edit.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Hormona.App.Dominio;
using Hormona.App.Persistencia;

namespace Hormona.App.Pages_BDFamiliar
{
    public class EditModel : PageModel
    {
  private readonly IRepositorioFamiliar RepositorioFamiliar;
        [BindProperty]
        public Familiar Familiar {get; set;}
        public  EditModel(IRepositorioFamiliar RepositorioFamiliar){
            this.RepositorioFamiliar = RepositorioFamiliar;
        }
        public IActionResult OnGet(int id)
        {
                Familiar=RepositorioFamiliar.GetFamiliar(id);
                if(Familiar==null){
                    return RedirectToPage("./NotFound");
                }
                else{
                    return Page();
                }
        }
        public IActionResult OnPostEdit(){
            Familiar=RepositorioFamiliar.UpdateFamiliar(Familiar);
           return RedirectToPage("Index");
    }
}
}

Hormona.App/Hormona.App.Presentacion/Pages/BDFamiliar/Index.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Hormona.App.Dominio;
using Hormona.App.Persistencia;

namespace Hormona.App.Pages_BDFamiliar
{
    public class IndexModel : PageModel
    {
        private readonly IRepositorioFamiliar RepositorioFamiliar; 
        public IEnumerable<Familiar> familiares {get; set;}   
        public IndexModel(IRepositorioFamiliar RepositorioFamiliar){
            this.RepositorioFamiliar= RepositorioFamiliar;

        }
        public void OnGet()
        {
            familiares=RepositorioFamiliar.GetAllFamiliares();
        }
    }
}

Hormona.App/Hormona.App.Presentacion/Pages/BDPacientes/Create.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Hormona.App.Dominio;
using Hormona.App.Persistencia;

namespace Hormona.App.Pages_BDPacientes
{
    public class CreateModel : PageModel
    {
        private readonly IRepositorioPaciente RepositorioPaciente;
        [BindProperty]
        public Paciente Paciente{get; set;}
        public CreateModel(IRepositorioPaciente RepositorioPaciente){
            this.RepositorioPaciente =RepositorioPaciente;
        }
        public void OnGet()
        {
        }
         public IActionResult OnPostSave(){
            Paciente=RepositorioPaciente.AddPaciente(Paciente);
            return RedirectToPage("Index");
                
            }
}
}

Hormona.App/Hormona.App.Presentacion/Pages/BDPacientes/Delete.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Hormona.App.Dominio;
using Hormona.App.Persistencia;

namespace Hormona.App.Pages_BDPacientes
{
    public class DeleteModel : PageModel
    {
         private readonly IRepositorioPaciente RepositorioPaciente;
        [BindProperty]
        public Paciente Paciente {get; set;}
        public DeleteModel(IRepositorioPaciente RepositorioPaciente){
           this.RepositorioPaciente = RepositorioPaciente;
        }
        public IActionResult OnGet(int id)
        {
                Paciente=RepositorioPaciente.GetPaciente(id);
                if(Paciente==null){
                    return RedirectToPage("./NotFound");
                }
                else{
                    return Page();
                }
        }
        public IActionResult OnPostDelete(){
            RepositorioPaciente.DeletePaciente(Paciente.id);
            return RedirectToPage("Index");
        }
    }
}

Hormona.App/Hormona.App.Presentacion/Pages/BDPacientes/Details.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Hormona.App.Dominio;
using Hormona.App.Persistencia;
namespace Hormona.App.Pages_BDPacientes
{
    public class DetailsModel : PageModel
    {
         private readonly IRepositorioPaciente RepositorioPaciente; 
        public Paciente Paciente {get; set;}   
        public Pediatra Pediatra {get; set;}
        public DetailsModel(IRepositorioPaciente RepositorioPaciente){
            this.RepositorioPaciente= RepositorioPaciente;

        }
        public IActionResult OnGet(int id)
        {
            Paciente=RepositorioPaciente.GetPaciente(id);
            if(Paciente==null){
                return RedirectToPage(",/NotFound");
            }
            else{
                if(RepositorioPaciente.ConsultarPediatra(id)==null){
                    Pediatra=new Pediatra{
                        nombre="Sin Asignar"
                    };
                    Paciente.Pediatra=Pediatra;
                }else{
                    Paciente.Pediatra=RepositorioPaciente.ConsultarPediatra(id);
                }
                return Page();
            }

        }
    }
}

Hormona.App/Hormona.App.Presentacion/Pages/BDPacientes/Edit.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Hormona.App.Dominio;
using Hormona.App.Persistencia;

namespace Hormona.App.Pages_BDPacientes
{
    public class EditModel : PageModel
    {
        private readonly IRepositorioPaciente RepositorioPaciente;
        [BindProperty]
        public Paciente Paciente {get; set;}
        public  EditModel(IRepositorioPaciente RepositorioPaciente){
            this.RepositorioPaciente = RepositorioPaciente;
        }
        public IActionResult OnGet(int id)
        {
                Paciente=RepositorioPaciente.GetPaciente(id);
                if(Paciente==null){
                    return RedirectToPage("./NotFound");
                }
                else{
                    return Page();
                }
        }
        public IActionResult OnPostEdit(){
            Paciente=RepositorioPaciente.UpdatePaciente(Paciente);
           return RedirectToPage("Index");
        }
    }
}

Hormona.App/Hormona.App.Presentacion/Pages/BDPediatras/Create.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Hormona.App.Dominio;
using Hormona.App.Persistencia;


namespace Hormona.App.Pages_BDPediatras
{
    public class CreateModel : PageModel
    {
private readonly IRepositorioPediatra RepositorioPediatra;
        [BindProperty]
        public Pediatra Pediatra{get; set;}
        public CreateModel(IRepositorioPediatra RepositorioPediatra) {
            this.RepositorioPediatra = RepositorioPediatra;
        }
        public void OnGet()
        {
        }
        public IActionResult OnpostSave(){
          //  if(ModelState.IsValid){
                Pediatra=RepositorioPediatra.AddPediatra(Pediatra);
                return RedirectToPage("Index");
           // }
           // else{
               // return Page();
            //}
        }
    }
}

Hormona.App/Hormona.App.Presentacion/Pages/MPacientes/Create.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Hormona.App.Dominio;
using Hormona.App.Persistencia;

namespace Hormona.App.Pages_MPacientes
{
    public class CreateModel : PageModel
    {
        private readonly IRepositorioPacienteMemoria RepositorioPacienteMemoria;
        [BindProperty]
        public Paciente Paciente{get; set;}
        public CreateModel(IRepositorioPacienteMemoria RepositorioPacienteMemoria) {
            this.RepositorioPacienteMemoria = RepositorioPacienteMemoria;
        }
        public void OnGet()
        {
        }
        public IActionResult OnpostSave(){
          //  if(ModelState.IsValid){
                Paciente=RepositorioPacienteMemoria.Add(Paciente);
                return RedirectToPage("Index");
           // }
           // else{
               // return Page();
            //}
        }
    }
}

Hormona.App/Hormona.App.Presentacion/Pages/MPacientes/Delete.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace Hormona.App.Pages_MPacientes
{
    public class DeleteModel : PageModel
    {
        public void OnGet()
        {
        }
    }
}

Hormona.App/Hormona.App.Presentacion/Pages/MPacientes/Details.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Hormona.App.Dominio;
using Hormona.App.Persistencia;

namespace Hormona.App.Pages_MPacientes
{
    public class DetailsModel : PageModel
    {
         private readonly IRepositorioPacienteMemoria RepositorioPacienteMemoria; 
        public Paciente Paciente {get; set;}   
        public DetailsModel(IRepositorioPacienteMemoria RepositorioPacienteMemoria){
            this.RepositorioPacienteMemoria= RepositorioPacienteMemoria;

        }
        public IActionResult OnGet(int id)
        {
            Paciente=RepositorioPacienteMemoria.Get(id);
            if(Paciente==null){
                return RedirectToPage(",/NotFound");
            }
            else{
                return Page();
            }
        }
    }
}

Hormona.App/Hormona.App.Presentacion/Pages/MPacientes/Edit.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace Hormona.App.Pages_MPacientes
{
    public class EditModel : PageModel
    {
        public void OnGet()
        {
        }
    }
}

Hormona.App/Hormona.App.Presentacion/Pages/MPediatras/Create.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Hormona.App.Dominio;
using Hormona.App.Persistencia;

namespace HospiEnCasa.App.Pages_MPediatras
{
    public class CreateModel : PageModel
    {
 private readonly IRepositorioPediatraMemoria RepositorioPediatraMemoria;
        [BindProperty]
        public Pediatra Pediatra{get; set;}
        public CreateModel(IRepositorioPediatraMemoria RepositorioPediatraMemoria) {
            this.RepositorioPediatraMemoria = RepositorioPediatraMemoria;
        }
        public void OnGet()
        {
        }
        public IActionResult OnpostSave(){
          //  if(ModelState.IsValid){
                Pediatra=RepositorioPediatraMemoria.Add(Pediatra);
                return RedirectToPage("Index");
           // }
           // else{
               // return Page();
            //}
        }
    }
}

Hormona.App/Hormona.App.Presentacion/Pages/MPediatras/Delete.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace HospiEnCasa.App.Pages_MPediatras
{
    public class DeleteModel : PageModel
    {
        public void OnGet()
        {
        }
    }
}

Hormona.App/Hormona.App.Presentacion/Pages/MPediatras/Details.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace HospiEnCasa.App.Pages_MPediatras
{
    public class DetailsModel : PageModel
    {
        public void OnGet()
        {
        }
    }
}

Hormona.App/Hormona.App.Presentacion/Pages/MPediatras/Edit.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace HospiEnCasa.App.Pages_MPediatras
{
    public class EditModel : PageModel
    {
        public void OnGet()
        {
        }
    }
}

Hormona.App/Hormona.App.Presentacion/Pages/BDFamiliar/Create.cshtml
@page
@model Hormona.App.Pages_BDFamiliar.CreateModel
@{
}
<form method="post">
    <div asp-validation-sumary="ModelOnly"></div>
    <div class="form-group">
        <label>Nombre</label>
        <input asp-for="Familiar.nombre" placeholder="Digite el nombre del Familiar" class="form-control"/>    
    </div>
     <div class="form-group">
        <label>Apellidos</label>
        <input asp-for="Familiar.apellido" placeholder="Digite los apellidos del Familiar" class="form-control"/>
    </div>
     <div class="form-group">
        <label>Telefono</label>
        <input asp-for="Familiar.telefono" placeholder="Digite el telefono del Familiar" class="form-control"/>
    </div>
     </div>
     <div class="form-group">
        <label>Documento</label>
        <input asp-for="Familiar.documento" placeholder="Digite el documento del Familiar" class="form-control"/>
    </div>
    <label>Sexo</label>
     <div class="form-group">
        <select asp-for="Familiar.sexos" class="form-control">
            <option selected>Sexo..</option>
            <option value=0>Femenino</option>
            <option value=1>Masculino</option>
        </select>

    </div>
     </div>
     <div class="form-group">
        <label>Parentesco</label>
        <input asp-for="Familiar.parentesco" placeholder="Digite el codigo del Familiar" class="form-control"/>
    </div>
     </div>
     <div class="form-group">
        <label>Email</label>
        <input asp-for="Familiar.email" placeholder="Digite el registro del Familiar" class="form-control"/>
    </div>
          
    <button type="submit" class="btn btn-primary" asp-page-handler="Save">Crear</button>
</form>

Hormona.App/Hormona.App.Presentacion/Pages/BDFamiliar/Delete.cshtml
@page
@model Hormona.App.Pages_BDFamiliar.DeleteModel
@{
}
<h1>Seguro quieres eliminar este familiar</h1>
<div>
    <h4>Familiar</h4>
    <d1 class="row">
        <dt class="col-sm-2">Nombre</dt>
        <dd class="col-sm-10">@Model.Familiar.nombre</dd>
         <dt class="col-sm-2">Apellido</dt>
        <dd class="col-sm-10">@Model.Familiar.apellido</dd>
         <dt class="col-sm-2">Telefono</dt>
        <dd class="col-sm-10">@Model.Familiar.telefono</dd>
         <dt class="col-sm-2">Sexo</dt>
        <dd class="col-sm-10">@Model.Familiar.sexos</dd>
        <dt class="col-sm-2">Documento</dt>
        <dd class="col-sm-10">@Model.Familiar.documento</dd>
         <dt class="col-sm-2">Parentesco</dt>
        <dd class="col-sm-10">@Model.Familiar.parentesco</dd>
         <dt class="col-sm-2">Email</dt>
        <dd class="col-sm-10">@Model.Familiar.email</dd>
   
  

    
    </d1>
</div>
<form method="post">
    <input type="hidden" asp-for="Familiar.id"/>
    <button type="submit" class="btn btn-primary" asp-page-handler="Delete">Delete</button>
<a asp-page="./Index">Back to list</a>
</form>

Hormona.App/Hormona.App.Presentacion/Pages/BDFamiliar/Details.cshtml
@page
@model Hormona.App.Pages_BDFamiliar.DetailsModel
@{
}
<h1>Details</h1>
<div>
    <h4>Familiar</h4>
    <d1 class="row">
        <dt class="col-sm-2">Nombre</dt>
        <dd class="col-sm-10">@Model.Familiar.nombre</dd>
         <dt class="col-sm-2">Apellido</dt>
        <dd class="col-sm-10">@Model.Familiar.apellido</dd>
         <dt class="col-sm-2">Telefono</dt>
        <dd class="col-sm-10">@Model.Familiar.telefono</dd>
         <dt class="col-sm-2">Sexo</dt>
        <dd class="col-sm-10">@Model.Familiar.sexos</dd>
         <dt class="col-sm-2">Documento</dt>
        <dd class="col-sm-10">@Model.Familiar.documento</dd>
         <dt class="col-sm-2">Parentesco</dt>
        <dd class="col-sm-10">@Model.Familiar.parentesco</dd>
         <dt class="col-sm-2">Email</dt>
        <dd class="col-sm-10">@Model.Familiar.email</dd>
        
    </d1>
</div>

Hormona.App/Hormona.App.Presentacion/Pages/BDFamiliar/Edit.cshtml
@page
@model Hormona.App.Pages_BDFamiliar.EditModel
@{
}
<form method="post">
    <input type="hidden" asp-for="Familiar.id"/>
    <div class="form-group">
        <label>Nombre</label>
        <input asp-for="Familiar.nombre" placeholder="Digite el nombre del Familiar" class="form-control"/> 
    </div>
     <div class="form-group">
        <label>Apellidos</label>
        <input asp-for="Familiar.apellido" placeholder="Digite los apellidos del Familiar" class="form-control"/>
    </div>
     <div class="form-group">
        <label>Telefono</label>
        <input asp-for="Familiar.telefono" placeholder="Digite el telefono del Familiar" class="form-control"/> 
    </div>
     </div>
     <div class="form-group">
        <label>Documento</label>
        <input asp-for="Familiar.documento" placeholder="Digite el documento del Familiar" class="form-control"/>
    </div>
    <label>Sexo</label>
     <div class="form-group">
        <select asp-for="Familiar.sexos" class="form-control">
            <option selected>Sexo..</option>
            <option value=0>Femenino</option>
            <option value=1>Masculino</option>
        </select>

    </div>
     </div>
     <div class="form-group">
        <label>Parentesco</label>
        <input asp-for="Familiar.parentesco" placeholder="Digite el parentesco del Familiar" class="form-control"/>
    </div>
     </div>
     <div class="form-group">
        <label>Email</label>
        <input asp-for="Familiar.email" placeholder="Digite la direccion del Familiar" class="form-control"/>
      </div>
            </div>
    <button type="submit" class="btn btn-primary" asp-page-handler="Edit">Editar</button>
</form>

Hormona.App/Hormona.App.Presentacion/Pages/BDFamiliar/Index.cshtml
@page
@model Hormona.App.Pages_BDFamiliar.IndexModel
@{
}
<h1>Lista de familiares</h1>
<table class="table table-bordered">
    <thead>
        <tr>
            <th scope="col">Nombre</th>
            <th scope="col">Apellidos</th>
            <th scope="col">Telefeno</th>
            <th scope="col">Sexo</th>
            <th scope="col">Documento</th>
            <th scope="col">Parentesco</th>
            <th scope="col">Email</th>
            <th scope="col">Opciones<a asp-page="./Create">
                    <span class="material-icons">person_add</span></a></th>


        </tr>
    </thead>
    @foreach (var familiar in Model.familiares)
    {
        <tbody>
            <tr>
                <td>@familiar.nombre</td>
                <td>@familiar.apellido</td>
                <td>@familiar.telefono</td>
                <td>@familiar.sexos</td>
                <td>@familiar.documento</td>
                <td>@familiar.parentesco</td>
                <td>@familiar.email</td>
                <td>
                    <a asp-page="./Details" asp-route-id="@familiar.id">
                        <span class="material-icons">description</span></a>
                    <a asp-page="./Edit" asp-route-id="@familiar.id">
                        <span class="material-icons">edit</span></a>
                    <a asp-page="./Delete" asp-route-id="@familiar.id">
                        <span class="material-icons">delete</span></a>
                </td>
            </tr>

        </tbody>

        {
        }
    }
</table>